name: Auto Comment

on:
  workflow_dispatch:
  #schedule:
    #- cron: '15,45 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/python:v1.61.0-noble
      options: --user 1001

    steps:
      - uses: actions/checkout@v4

      - name: Install Python package
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py